name: GeekHarder
favicon: null
layout_spectrum: 0.7108681260142475
typography_spectrum: 0.8047673173714429
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1838fb'
    - '#ffffff'
    - '#020202'
    - '#646464'
    - '#b2b2b2'
  brandStrength: 0.647015594644472
  lightness: 0.9133802622091025
  saturation: 0.29738582484424114
  rhythmicContrast: 0.25274340412579477
purpose: []
